String intro(); 
//char setup_game();
int situtation1(String  n);
int  situtation2(String  n);
int situtation3(String  n);
int mfmf_route(String  n);
int srr_route(String  n);
int urtnk_route(String  n);
int skt_route(String  n);
int mfmf_gEnd();
int mfmf_bEnd();
int srr_gEnd();
int srr_bEnd();
int urtk_gEnd();
int urtk_bEnd();
int skt_gEnd();
int skt_bEnd(); 
