String intro(); 
//char setup_game();
int situtation1(String  n);
int  situtation2(String  n);
int situtation3(String  n);
int mfmf_route(String n);
int srr_route(String  n);
int urtnk_route(String  n);
int skt_route(String  n);
void mfmf_gEnd(String  n);
void mfmf_bEnd(String  n);
void srr_gEnd(String  n);
void srr_bEnd(String  n);
void urtnk_gEnd(String  n);
void urtnk_bEnd(String  n);
void skt_gEnd(String  n);
void skt_bEnd(String  n); 
void common_ending(String n);
